major refactor

diff --git a/.local/mybin/dmenu-scrot b/.local/mybin/dmenu-scrot
--- a/.local/mybin/dmenu-scrot
+++ b/.local/mybin/dmenu-scrot
@@ -3,48 +3,60 @@
 # Dependencies:
 # - scrot
 # - dmenu
+# - dmenu-choose-dir (helper script)
+# - dmenu-noyes (helper script)
 
 # TODO:
 # - testing
-# - move to the specified directory
-# - give picture the specified name (check for overwritting existing file)
-# - test for existence of $dir/$filename
-# - change file name for selection and active window
+# - clean up script
 
-DEFAULT_NAME="Scrot default"
-DEFAULT_DIR="$MY_PIX_HOME/shots"
+# Define these variables if they are not set as environment variables
+[ -z "${DMENU}" ] && export DMENU='dmenu -i -p'
+export DMENU="dmenu -i -p"
+
+# Global variables
+# shellcheck disable=SC2016
+DEFAULT_NAME="$(date '+%Y-%m-%d-%H%M%S')_scrot"
+DEFAULT_DIR="$MY_PICTURES_DIR/shots"
+DEFAULT_FULL_PATH="${DEFAULT_DIR}${DEFAULT_NAME}"
 [ -d "$DEFAULT_DIR" ] || mkdir -p "$DEFAULT_DIR"
+SEARCH_DIRS="${MY_PICTURES_DIR} \
+             ${MY_DOCUMENTS_DIR}/mnt \
+             ${MY_DESKTOP_DIR} \
+             /mnt"
+
+usage() {
+    >&2 cat << EOF
+Usage: $0
+EOF
+}
+
+take_scrot() {
+    # shellcheck disable=SC2016,SC2086
+    scrot "$1" $2 -e 'mv $f $$MY_PICTURES_DIR/shots/' || return 1
+    [ "${DEFAULT_FULL_PATH}" = "${full_path}" ] || mv "${DEFAULT_FULL_PATH}" "${full_path}"
+    return
+}
 
 options='Selection\nFullscreen\nActive Window'
-choice=$(echo "$options" | dmenu -i -p 'Screenshot options:') || exit 1
-filename=$(echo "$DEFAULT_NAME" | dmenu -i -p 'Enter file name (no extension):') || "$DEFAULT_NAME"
-dir=$(du '/media' "$HOME/Pictures" | tac - | cut -f 2 | dmenu -i -p 'Safe Picture in:') || "$DEFAULT_DIR"
-
-if [ ! -d "$dir" ]; then
-    mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$dir does not exist. Create it?") || exit 1
-    [ "$mkdiryn" = "Yes" ] && (mkdir -p "$dir" || sudo -A mkdir -p "$dir")
-    [ "$mkdiryn" = "No" ] && dir="$DEFAULT_DIR"
-fi
+choice=$(echo "$options" | ${DMENU} 'Screenshot options:') || exit 1
+filename="$(echo "$DEFAULT_NAME" | ${DMENU} 'Enter file name (no extension):').png" || exit 1
+dir="$(dmenu-choose-dir '3' "${SEARCH_DIRS}" "Where to store the picture?")" || exit 1
+full_path="${dir}/${filename}" 
 
 # test for existence of $dir/$filename
+[ -f "${full_path}" ] && ! dmenu-noyes "${full_path} already exists, overwite it?" && exit 1
 
 case "$choice" in
     'Fullscreen')
         dim=$(xwininfo -root | grep geometry | grep -oP '\d+x\d+')
         w=$(echo "$dim" | cut -d x -f 1)
         h=$(echo "$dim" | cut -d x -f 2)
-        # shellcheck disable=SC2016,SC2086
-        if [ "$filename" = "$DEFAULT_NAME" ]; then
-            scrot -a 0,0,$w,$h -e 'mv $f $$HOME/Pictures/shots'
-        else
-            scrot "${filename}.png" -a 0,0,$w,$h -e 'mv $f $$HOME/Pictures/shots' 
-        fi ;;
-    'Selection')
-        # shellcheck disable=SC2016
-        scrot -se 'mv $f $$HOME/Pictures/shots' ;;
-    'Active Window')
-        # shellcheck disable=SC2016
-        scrot -ue 'mv $f $$HOME/Pictures/shots' ;;
-    *)
-        >&2 echo 'Wrong option supplied' && exit 1 ;;
+        take_scrot "${DEFAULT_NAME}" "-a 0,0,$w,$h" ;;
+    'Selection')     
+        take_scrot "${DEFAULT_NAME}" '-s' ;;
+    'Active Window') 
+        take_scrot "${DEFAULT_NAME}" '-u' ;;
+    *) usage && exit 1 ;;
 esac
+exit
